spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
---
spring:
  config:
    activate:
      on-profile: docker
    import: optional:configserver:http://config-server:8888
