spring:
  application:
    name: eureka-server
  cloud:
    discovery:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000

---
spring:
  profiles: order-service
  application:
    name: order-service
  server:
    port: 8081
  datasource:
    url: jdbc:mysql://localhost:3306/order_service
    username: your_username
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update

---
spring:
  profiles: product-service
  application:
    name: product-service
  server:
    port: 8082
  datasource:
    url: jdbc:mysql://localhost:3306/product_service
    username: your_username
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update

---
spring:
  profiles: order-item-service
  application:
    name: order-item-service
  server:
    port: 8083
  datasource:
    url: jdbc:mysql://localhost:3306/order_item_service
    username: your_username
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update

