# application.yml in Discovery Server
spring:
  application:
    name: discovery-server
  config:
    import: optional:configserver:http://localhost:8888  # Used for local development

---
spring:
  config:
    activate:
      on-profile: docker
    import: optional:configserver:http://config-server:8888  # Used in Docker
